---
- name: deploy resume.kungfoo.info to static server
  hosts: all
  gather_facts: no
  remote_user: root

  tasks:
  - name: test
    ansible.builtin.command: ls -al
    register: cmd_output

  - debug:
      var: cmd_output.stdout_lines

  - name: copy files
    ansible.builtin.copy:
      src: ../../.output/public/
      dest: /usr/local/www/resume.kungfoo.info
